### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by kunjee17** [pd29/vscode-fantomas-fmt#1]
Hi, Thanks for nice plugin. I was thinking of installing and hooking up in Fake but if vs code is giving it then I would be better of changing my development pipeline. 

But I couldn't find out any getting started guide or even commands that I can fire up. Even format command is not working for F# files. 

it would be great if you can provide some getting started guide to use this tool.

**Comment by pd29** [comment]
Hi,
actually it should work by executing _Format document_ (Shift+Alt+F windows,  Ctrl+Shift+I linux).
Maybe a bug is causing the problem for you.
If so, could you please tell me your os, dotnet version, and a dump of console log from vscode development tools?

**Comment by kunjee17** [comment]
@pd29 that start working. I guess I was requiring a restart. Sorry for false alarm. I am closing the issue. Thanks again for nice tool.
