### ISSUE TITLE
Adjust default settings to F# code formatting guidelines

### ISSUE THREAD

**Issue by alfonsogarciacaro** [pd29/vscode-fantomas-fmt#7]
Three of the default settings doesn't seem to match the [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-lists-and-arrays). Maybe they should be changed?

- noSpaceAfterComma -> should be false
- noSpaceAfterSemiColon -> should be false
- noSpaceAroundDelimiter -> should be false

**Comment by alfonsogarciacaro** [comment]
Related: https://github.com/fsprojects/fantomas/issues/372#issuecomment-442434500

It seems the VS Code extension is using fantomas CLI arguments (with a `no` in front) but [the defaults from the API](https://github.com/fsprojects/fantomas/blob/203eb7e8e46d5b73476873381e9b457e4acb33e6/src/Fantomas/FormatConfig.fs#L28) so the effect is the opposite.

Another solution could be to remove the `no` prefix (and adjust the behaviour accordingly). This may be more clear for users.

**Comment by pd29** [comment]
Thank you! 
I embraced your suggestion to remove the `no` prefix.

**Comment by alfonsogarciacaro** [comment]
Thanks for fixing and thanks a lot for the extension, it's incredibly useful! 🥇
