### ISSUE TITLE
Indent match case in new line

### ISSUE THREAD

**Issue by edongashi** [pd29/vscode-fantomas-fmt#9]
Formatting gives me linter warnings because the case body is not indented:

![image](https://user-images.githubusercontent.com/12145268/51955561-948aa100-2444-11e9-8e05-bb4d3271db76.png)

Any way to configure it to this?

![image](https://user-images.githubusercontent.com/12145268/51955615-bf74f500-2444-11e9-895c-0b4c0391d13c.png)

Thanks!

**Comment by paolodellepiane** [comment]
this extension only calls fantomas to format code, doesn't provide any linting functionality
